### ISSUE TITLE
mana eksistence

### ISSUE THREAD

**Issue by tomsval** [IceSalesman/volleyball-webapp#1]
ir problema jo es eksisteju

**Comment by IceSalesman** [comment]
to var viegli atrisinat 😉

**Comment by tomsval** [comment]
ja tas ir tik triviali, tad ka? 🤔😔

**Comment by IceSalesman** [comment]
ir tadi 2 smiekligi torni kipsala, iesaku tos

**Comment by tomsval** [comment]
paldies! 😊

**Comment by tomsval** [comment]
paldies! 😊
